# Site settings site.title
title: New Golden Sea |Vận chuyển đường biển| Vận chuyển container| Vận chuyển giá rẻ
url: "https://minh-vu.github.io"   # domain-name 
baseurl: "/golden"                      # repo-name 
description: "Công ty vận chuyển hàng hóa giá rẻ, uy tín qua các đường như: hàng không, đường biển, nội địa,...Sẵn sàng phục vụ quý khách hàng | 0972.967.137"

copyright_name: GoldenLogistic #footer
header-img: img/home-bg.jpg
email: nguyencongvu@gmail.com
author: "Vu, Nguyen"

language: "vi" #seo
locale: "en-US"  #seo
keyword: "vận chuyển" #seo
og_image: "assets/img/small/logo.png" #seo
comment_activate: false #set false or "" to disabled 

#cdn
cdn_url : "http://cdn.digitalife.top:8080"

#social account --> EDIT 
twitter_username: "vunc"
github_username:  digitalife-top
facebook_username:  "nguyencongvu"
facebook_app_id:  "303370230021409"
facebook_admins: "791078183"
email_username:  nguyencongvu@gmail.com
google_plus_id:  "101600677672081932719"
google_form: "https://goo.gl/forms/UNBSCvJQMnKi3WRZ2" # POPUP contact-form 

#footer contact vcard --> EDIT 
contact_name: "CÔNG TY TNHH GIAO NHẬN VẬN CHUYỂN QUỐC TẾ TÂN BIỂN VÀNG" 
contact_call_to: "+84937980003"
contact_phone: "(08) 2 253 3335"
contact_fax: " (08) 2 253 3334 "
contact_address: "Tháp E , Lầu 3 , Phòng 16 ,Tòa Nhà Lexington, Số 67 Đường Mai Chí Thọ, Phường An Phú , Quận 2"
contact_city: "TP.Hồ Chí Minh"
contact_country: "Vietnam"

# Analytics --> EDIT if needed 
# google_tracking_id:
google_site_verification : "UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y"
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :
google_custom_search     : 
#google_custom_search     : "ibfrmo7jwwm" # syiovql90j8

# ================ DO-NOT-EDIT =========================
# Build settings
markdown: kramdown
highlighter: rouge
permalink: none #date pretty ordinal 
paginate: 5
paginate_path: "blogs/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: 
  - jekyll-paginate
  - jekyll-feed

defaults:
  -
    scope:
      path: "/"
      type: "pages"
    values:
      layout: materialize/landingpage
      author: "Vu, Nguyen"
      #header-img: "img/contact-bg.jpg"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: materialize/page
      author: "Vu, Nguyen"
      #header-img: "img/contact-bg.jpg"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: materialize/post
      author: "Vu, Nguyen"
